#!/bin/bash
service nginx status > output.txt
if grep -q "running" output.txt; then
echo "nginx service is running"
else
echo "service is stopped" | mail -s "nginx service is stopped " jaideepojha115@gmail.com
fi
========================================================================================================
#!/bin/bash
# Check if Nginx is running
if systemctl is-active --quiet nginx; then
    echo "Nginx is running."
else
    echo "Nginx is not running."
fi
